package com.grtship.core.enumeration;

/**
 * The EntityType enumeration.
 */
public enum EntityType {
    CUSTOMER, VENDOR, EXPORTER, IMPORTER, FORWARDER, CONSOLIDATOR, IATA, CUSTOMSBROKER, LINE, SHIPPINGLINEAGENT, COLOADER, SURVEYOR, CFS, TRANSPORTER, TRAINOPERATOR, TRANSPORTERGTA, TRANSPORTERLSP
}
