spring:
  servlet:
     multipart:
       max-file-size: 15MB
  profiles:
    active: uat   
server:
  port: 8087
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024  
  servlet:
    context-path: /notification
    
    
# KAFKA-CONFIGURATION
kafka: # to configure kafka just un-comment this property
  bootstrap :
    servers: localhost:9092
  consumer:
    group_id: notification-service
    offset :
      reset_config : latest
    enable : 
      auto_commit : true
    key : 
      deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value : 
      deserializer: org.apache.kafka.common.serialization.StringDeserializer
    auto : 
      commit : 
        interval_ms : 10000 
        
  producer:
    key :
      serializer: org.apache.kafka.common.serialization.StringSerializer
    value: 
      serializer: org.apache.kafka.common.serialization.StringSerializer
    lingerms: 2
    retries : 2
    acks: 1 
    compression_type: lz4
    request_timeout_ms: 59000  